### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/queryverse.github.io#7]
Would be nice if we had a nice queryverse logo :) There are a couple of examples floating around where folks used the colors from the default julia logo, and did some variant of that. That might be a good model. Or not, I really have zero design skills...

**Comment by davidanthoff** [comment]
Wow, cool, they look great!

**Comment by dotvhs** [comment]
Thanks, I will clean them up a bit and send you SVG and PNGs if that's alright, unless you need something specific?

**Comment by davidanthoff** [comment]
@TonyLianLong I think we would need it as a SVG, correct?

**Comment by TonyLianLong** [comment]
@davidanthoff Yes, I think so.

**Comment by davidanthoff** [comment]
@dotvhs Just checking in, I'd love to use that logo!

**Comment by dotvhs** [comment]
Oh damn, I'm sorry I forgot about it!

Here are files:
[Archive.zip](https://github.com/queryverse/queryverse.github.io/files/2850015/Archive.zip)

**Comment by davidanthoff** [comment]
Fantastic, thanks!

@TonyLianLong could you switch the logos?

**Comment by TonyLianLong** [comment]
Yeah, sure.

**Comment by TonyLianLong** [comment]
Added, see [here](https://queryverse-webstaging.github.io/)

**Comment by davidanthoff** [comment]
Perfect, I merged that into the main site and it is now live!

Thanks so much, @dotvhs!!
